<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/app/bootstrap.php';
require_once dirname(__DIR__).'/app/pdf.php';
require_once dirname(__DIR__).'/app/quote_actions.php';

$page=(string)($_GET['page']??'public');
$action=(string)($_POST['action']??$_GET['action']??'');
$errors=[];

function shell_start(string $title,string $heading=''): void {
    $user=current_user(); $active=(string)($_GET['page']??'dashboard');
    echo '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.e($title).' · Cotizaciones Metalrubber</title><link rel="stylesheet" href="assets/style.css"></head><body><div class="shell"><aside class="side"><a class="brand" href="index.php?page=dashboard"><span class="brand-mark">M</span><span><strong>METALRUBBER</strong><small>Cotizaciones</small></span></a><nav class="nav">';
    foreach(['dashboard'=>'Panel principal','quote_new'=>'Nueva cotización','requests'=>'Solicitudes','quotes'=>'Cotizaciones','clients'=>'Clientes'] as $k=>$label) echo '<a class="'.($active===$k?'active':'').'" href="'.($k==='quote_new'?'quote_new.php':'index.php?page='.$k).'">'.e($label).'</a>';
    echo '</nav><div class="side-footer">Hualpén, Chile<br>41 317 7199<br>metalrubber@gmail.com</div></aside><div class="main"><header class="top"><button class="menu" onclick="document.querySelector(\'.shell\').classList.toggle(\'menu-open\')">☰</button><h1>'.e($heading?:$title).'</h1><div class="user">'.e($user['name']??'Administrador').' · <a href="logout.php">Salir</a></div></header><main class="content">';
    foreach(consume_flash() as $f) echo '<div class="alert '.e($f['type']).'">'.e($f['message']).'</div>';
}
function shell_end(): void { echo '</main></div></div></body></html>'; }
function status_select(string $name,string $value): void { echo '<select class="select" name="'.e($name).'">'; foreach(request_statuses() as $s) echo '<option value="'.e($s).'" '.($s===$value?'selected':'').'>'.e(status_label($s)).'</option>'; echo '</select>'; }
function public_head(): void { echo '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Solicitar cotización · Metalrubber</title><link rel="stylesheet" href="assets/style.css"></head><body>'; }

if($page==='public' && $_SERVER['REQUEST_METHOD']!=='POST' && $action===''){
    if(current_user()) redirect('index.php?page=dashboard');
    redirect('login.php');
}

if ($_SERVER['REQUEST_METHOD']==='POST' && $action==='public_submit') {
    try {
        verify_csrf();
        $required=['name','rut','email','phone','address','contact_name','service_product','technical_description'];
        foreach($required as $field) if(trim((string)($_POST[$field]??''))==='') $errors[]='Completa todos los campos obligatorios.';
        if(!filter_var($_POST['email']??'',FILTER_VALIDATE_EMAIL)) $errors[]='Ingresa un correo válido.';
        if(!valid_rut((string)($_POST['rut']??''))) $errors[]='El RUT no es válido.';
        if(!$errors) {
            $pdo=db(); $pdo->beginTransaction();
            $s=$pdo->prepare('SELECT id FROM clients WHERE rut=?'); $s->execute([trim((string)$_POST['rut'])]); $clientId=$s->fetchColumn();
            $data=[trim((string)$_POST['name']),trim((string)$_POST['email']),trim((string)$_POST['phone']),trim((string)$_POST['address']),trim((string)$_POST['contact_name'])];
            if($clientId){$s=$pdo->prepare('UPDATE clients SET name=?,email=?,phone=?,address=?,contact_name=? WHERE id=?');$s->execute([...$data,$clientId]);}
            else{$s=$pdo->prepare('INSERT INTO clients (name,rut,email,phone,address,contact_name) VALUES (?,?,?,?,?,?)');$s->execute([$data[0],trim((string)$_POST['rut']),$data[1],$data[2],$data[3],$data[4]]);$clientId=(int)$pdo->lastInsertId();}
            $number=next_number('SOL','quote_requests','request_number'); $s=$pdo->prepare('INSERT INTO quote_requests (request_number,client_id,service_product,technical_description,material,quantity,unit,measurements,required_deadline,observations) VALUES (?,?,?,?,?,?,?,?,?,?)');
            $s->execute([$number,$clientId,trim((string)$_POST['service_product']),trim((string)$_POST['technical_description']),trim((string)($_POST['material']??''))?:null,(float)($_POST['quantity']??0)?:null,trim((string)($_POST['unit']??''))?:null,trim((string)($_POST['measurements']??''))?:null,($_POST['required_deadline']??'')?:null,trim((string)($_POST['observations']??''))?:null]);
            $requestId=(int)$pdo->lastInsertId(); add_history('request',$requestId,null,'received','Solicitud pública recibida.'); upload_files($requestId); $pdo->commit(); redirect('index.php?sent='.rawurlencode($number));
        }
    } catch(Throwable $e) { if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack(); $errors[]=$e->getMessage(); }
}
if(isset($_GET['sent'])) { public_head(); echo '<div class="login-wrap" style="background:var(--paper)"><div class="login-card"><h1>Solicitud<br><em style="color:#b09d00;font-style:normal">recibida</em></h1><div class="alert success">Registramos la solicitud <strong>'.e((string)$_GET['sent']).'</strong>.</div><a class="btn btn-dark" href="index.php">Enviar otra solicitud</a></div></div></body></html>'; exit; }
if($page==='public' && $_SERVER['REQUEST_METHOD']!=='POST' && $action==='') {
    public_head(); echo '<main class="hero-public"><section class="public-copy"><p class="eyebrow" style="color:var(--yellow)">Metalrubber Ltda. · Hualpén, Chile</p><h1>Cuéntanos<br><em>qué necesitas.</em></h1><p>Fabricamos soluciones metalmecánicas y productos de caucho a la medida. Completa el formulario y nuestro equipo revisará tu requerimiento.</p><div class="public-contact">41 317 7199 · WhatsApp +56 9 9312 8000<br>metalrubber@gmail.com · metalrubber.cl</div><div class="actions"><a class="btn btn-primary" href="login.php">Acceso administrativo</a></div></section><section class="public-form"><p class="eyebrow">Solicitud de cotización</p><h2>Datos del requerimiento</h2>';
    foreach($errors as $err) echo '<div class="alert error">'.e($err).'</div>';
    echo '<form method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="public_submit">'.csrf_field().'<div class="form-grid">';
    $fields=[['name','Nombre o razón social *','text'],['rut','RUT *','text'],['email','Correo *','email'],['phone','Teléfono *','text'],['address','Dirección *','text'],['contact_name','Contacto responsable *','text'],['service_product','Servicio o producto solicitado *','text'],['material','Material','text'],['measurements','Medidas','text'],['quantity','Cantidad','number'],['unit','Unidad','text'],['required_deadline','Plazo requerido','date']];
    foreach($fields as $f) echo '<div class="field"><label for="'.$f[0].'">'.e($f[1]).'</label><input class="input" id="'.$f[0].'" name="'.$f[0].'" type="'.$f[2].'" '.($f[0]==='quantity'?'step="0.001" min="0"':'').' value="'.e($_POST[$f[0]]??'').'"></div>';
    echo '<div class="field full"><label>Descripción técnica *</label><textarea class="textarea" name="technical_description" required>'.e($_POST['technical_description']??'').'</textarea></div><div class="field full"><label>Adjuntos</label><input class="input" name="attachments[]" type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx,.dwg"><small>Máximo 10 MB por archivo.</small></div><div class="field full"><label>Observaciones</label><textarea class="textarea" name="observations">'.e($_POST['observations']??'').'</textarea></div></div><div class="actions"><button class="btn btn-dark">Enviar solicitud</button></div></form></section></main></body></html>'; exit;
}
if($page==='setup') {
    if((int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn()>0) redirect('login.php');
    if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$name=trim((string)$_POST['name']);$email=trim((string)$_POST['email']);$password=(string)$_POST['password'];if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<10)$errors[]='Usa datos válidos y una contraseña de al menos 10 caracteres.';else{$s=db()->prepare('INSERT INTO users (name,email,password_hash) VALUES (?,?,?)');$s->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT)]);redirect('login.php');}}
    echo '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Configuración inicial</title><link rel="stylesheet" href="assets/style.css"></head><body><main class="login-wrap"><form class="login-card" method="post"><h1>Primera<br><em style="color:#b09d00;font-style:normal">configuración</em></h1>';foreach($errors as $err)echo '<div class="alert error">'.e($err).'</div>';echo '<input type="hidden" name="action" value="setup">'.csrf_field().'<div class="field"><label>Nombre</label><input class="input" name="name" required></div><div class="field"><label>Correo</label><input class="input" type="email" name="email" required></div><div class="field"><label>Contraseña</label><input class="input" type="password" name="password" minlength="10" required></div><div class="actions"><button class="btn btn-primary">Crear administrador</button></div></form></main></body></html>';exit;
}
require_login();

if($action==='save_quote'){handle_save_quote_form();}

if($action==='request_status') { verify_csrf(); $id=(int)$_POST['request_id']; $new=(string)$_POST['status']; if(!in_array($new,request_statuses(),true)) exit('Estado inválido.'); $s=db()->prepare('SELECT status FROM quote_requests WHERE id=?');$s->execute([$id]);$old=$s->fetchColumn();db()->prepare('UPDATE quote_requests SET status=? WHERE id=?')->execute([$new,$id]);add_history('request',$id,(string)$old,$new,trim((string)($_POST['comment']??'')));flash('success','Estado actualizado.');redirect('index.php?page=request&id='.$id); }
if($action==='quote_status') { verify_csrf(); $id=(int)$_POST['quote_id'];$new=(string)$_POST['status'];if(!in_array($new,request_statuses(),true))exit('Estado inválido.');$s=db()->prepare('SELECT status,request_id FROM quotes WHERE id=?');$s->execute([$id]);$q=$s->fetch();if(!$q)exit('Cotización no encontrada.');db()->prepare('UPDATE quotes SET status=? WHERE id=?')->execute([$new,$id]);add_history('quote',$id,$q['status'],$new,trim((string)($_POST['comment']??'')));db()->prepare('UPDATE quote_requests SET status=? WHERE id=?')->execute([$new,$q['request_id']]);flash('success','Estado actualizado.');redirect('index.php?page=quote&id='.$id); }
if($action==='save_quote_legacy') {
    verify_csrf(); $requestId=(int)$_POST['request_id'];$issue=(string)($_POST['issue_date']??date('Y-m-d'));$expiry=(string)($_POST['expiry_date']??'');if(!$expiry||$expiry<$issue)exit('La fecha de vencimiento es obligatoria y válida.');
    $items=[];foreach((array)($_POST['description']??[]) as $i=>$desc){$desc=trim((string)$desc);if($desc!=='')$items[]=['description'=>$desc,'quantity'=>(float)($_POST['quantity'][$i]??0),'unit'=>trim((string)($_POST['unit'][$i]??'un')),'unit_price'=>(float)($_POST['unit_price'][$i]??0),'discount_percent'=>(float)($_POST['discount_percent'][$i]??0)];}
    if(!$items)exit('Agrega al menos un ítem.');$totals=calculate_totals($items,19);$pdo=db();$pdo->beginTransaction();$number=next_number('COT','quotes','quote_number');$s=$pdo->prepare('INSERT INTO quotes (quote_number,request_id,issue_date,expiry_date,status,tax_rate,subtotal,tax_amount,total,notes,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$number,$requestId,$issue,$expiry,'preparation',19,$totals['subtotal'],$totals['tax'],$totals['total'],trim((string)($_POST['notes']??'')),current_user()['id']]);$id=(int)$pdo->lastInsertId();$s=$pdo->prepare('INSERT INTO quote_items (quote_id,description,quantity,unit,unit_price,discount_percent,discount_amount,line_subtotal,line_total) VALUES (?,?,?,?,?,?,?,?,?)');foreach($items as $i){$c=calculate_item($i['quantity'],$i['unit_price'],$i['discount_percent']);$s->execute([$id,$i['description'],$i['quantity'],$i['unit'],$i['unit_price'],$i['discount_percent'],$c['discount'],$c['subtotal'],$c['subtotal']]);}db()->prepare('UPDATE quote_requests SET status="preparation" WHERE id=?')->execute([$requestId]);add_history('quote',$id,null,'preparation','Cotización creada.');$pdo->commit();flash('success','Cotización creada correctamente.');redirect('index.php?page=quote&id='.$id);
}
if($action==='pdf'){ $s=db()->prepare('SELECT q.*,c.name client_name,c.rut,c.email,c.phone,c.address,c.contact_name FROM quotes q JOIN quote_requests r ON r.id=q.request_id JOIN clients c ON c.id=r.client_id WHERE q.id=?');$s->execute([(int)$_GET['id']]);$q=$s->fetch();if(!$q)exit('Cotización no encontrada.');$s=db()->prepare('SELECT * FROM quote_items WHERE quote_id=?');$s->execute([$q['id']]);render_quote_pdf($q,$s->fetchAll());exit; }
if($action==='download_attachment'){ $s=db()->prepare('SELECT original_name,mime_type,relative_path FROM request_attachments WHERE id=?');$s->execute([(int)$_GET['id']]);$f=$s->fetch();$path=$f?dirname(__DIR__).'/public/uploads/'.$f['relative_path']:'';if(!$f||!is_file($path)){http_response_code(404);exit('Archivo no encontrado.');}header('Content-Type: '.$f['mime_type']);header('Content-Disposition: attachment; filename="'.basename($f['original_name']).'"');readfile($path);exit; }

if($page==='dashboard'){
    $stats=['received'=>(int)db()->query("SELECT COUNT(*) FROM quote_requests WHERE status='received'")->fetchColumn(),'pending'=>(int)db()->query("SELECT COUNT(*) FROM quotes WHERE status IN ('review','preparation')")->fetchColumn(),'sent'=>(int)db()->query("SELECT COUNT(*) FROM quotes WHERE status='sent'")->fetchColumn(),'accepted'=>(int)db()->query("SELECT COUNT(*) FROM quotes WHERE status='accepted'")->fetchColumn(),'total'=>(float)db()->query('SELECT COALESCE(SUM(total),0) FROM quotes')->fetchColumn()];$rows=db()->query('SELECT q.id,q.quote_number,q.total,q.status,c.name client_name FROM quotes q JOIN quote_requests r ON r.id=q.request_id JOIN clients c ON c.id=r.client_id ORDER BY q.created_at DESC LIMIT 8')->fetchAll();shell_start('Panel principal','Panel principal');echo '<p class="eyebrow">Resumen operativo</p><div class="cards">';foreach([['Solicitudes nuevas',$stats['received']],['Cotizaciones pendientes',$stats['pending']],['Cotizaciones enviadas',$stats['sent']],['Aceptadas',$stats['accepted']],['Monto total cotizado',money($stats['total'])]] as $i=>$m)echo '<div class="card metric '.($i===0?'accent':'').'"><span>'.e($m[0]).'</span><strong>'.e((string)$m[1]).'</strong></div>';echo '</div><section class="panel"><div class="panel-head"><h2>Últimas cotizaciones</h2><a class="btn btn-outline" href="index.php?page=quotes">Ver todas</a></div>';if(!$rows)echo '<div class="empty">Todavía no hay cotizaciones registradas.</div>';else{echo '<div class="table-wrap"><table class="table"><tr><th>Folio</th><th>Cliente</th><th>Estado</th><th>Total</th></tr>';foreach($rows as $r)echo '<tr><td><a href="index.php?page=quote&id='.$r['id'].'">'.e($r['quote_number']).'</a></td><td>'.e($r['client_name']).'</td><td><span class="status '.status_class($r['status']).'">'.e(status_label($r['status'])).'</span></td><td>'.money($r['total']).'</td></tr>';echo '</table></div>';}echo '</section>';shell_end();exit;
}
if($page==='requests'||$page==='quotes'){
    $quotes=$page==='quotes';$q=trim((string)($_GET['q']??''));$status=(string)($_GET['status']??'');$sql=$quotes?'SELECT q.id,q.quote_number number,q.issue_date,q.expiry_date,q.status,q.total,c.name client_name,c.rut FROM quotes q JOIN quote_requests r ON r.id=q.request_id JOIN clients c ON c.id=r.client_id WHERE 1=1':'SELECT r.id,r.request_number number,r.service_product,r.status,r.created_at,c.name client_name,c.rut FROM quote_requests r JOIN clients c ON c.id=r.client_id WHERE 1=1';$params=[];if($q!==''){$sql.=$quotes?' AND (q.quote_number LIKE ? OR c.name LIKE ? OR c.rut LIKE ?)':' AND (r.request_number LIKE ? OR c.name LIKE ? OR c.rut LIKE ?)';$params=["%$q%","%$q%","%$q%"];}if($status!==''){$sql.=' AND '.($quotes?'q':'r').'.status=?';$params[]=$status;}$sql.=' ORDER BY '.($quotes?'q.created_at':'r.created_at').' DESC';$s=db()->prepare($sql);$s->execute($params);$rows=$s->fetchAll();shell_start($quotes?'Cotizaciones':'Solicitudes',$quotes?'Cotizaciones':'Solicitudes');echo '<section class="panel"><div class="panel-head"><h2>'.($quotes?'Gestión de cotizaciones':'Solicitudes recibidas').'</h2><span class="hint">'.count($rows).' resultado(s)</span></div><div class="panel-body"><form class="filters" method="get"><input type="hidden" name="page" value="'.$page.'"><div class="field"><label>Buscar</label><input class="input" name="q" value="'.e($q).'" placeholder="Folio, cliente o RUT"></div><div class="field"><label>Estado</label>';status_select('status',$status);echo '</div><button class="btn btn-dark">Filtrar</button></form></div><div class="table-wrap"><table class="table"><tr><th>'.($quotes?'Folio':'Solicitud').'</th><th>Cliente</th><th>'.($quotes?'Fechas':'Requerimiento').'</th><th>Estado</th><th>'.($quotes?'Total':'Recepción').'</th></tr>';foreach($rows as $r)echo '<tr><td><a href="index.php?page='.($quotes?'quote':'request').'&id='.$r['id'].'">'.e($r['number']).'</a></td><td>'.e($r['client_name']).'<br><small>'.e($r['rut']).'</small></td><td>'.e($quotes?$r['issue_date'].' / '.$r['expiry_date']:$r['service_product']).'</td><td><span class="status '.status_class($r['status']).'">'.e(status_label($r['status'])).'</span></td><td>'.e($quotes?money($r['total']):date('d-m-Y H:i',strtotime($r['created_at']))).'</td></tr>';echo '</table></div>';if(!$rows)echo '<div class="empty">No encontramos registros con esos filtros.</div>';echo '</section>';shell_end();exit;
}
if($page==='clients'){ $q=trim((string)($_GET['q']??''));$like="%$q%";$s=db()->prepare('SELECT c.*,COUNT(r.id) request_count FROM clients c LEFT JOIN quote_requests r ON r.client_id=c.id WHERE c.name LIKE ? OR c.rut LIKE ? OR c.email LIKE ? GROUP BY c.id ORDER BY c.created_at DESC');$s->execute([$like,$like,$like]);$rows=$s->fetchAll();shell_start('Clientes','Clientes');echo '<section class="panel"><div class="panel-head"><h2>Clientes registrados</h2></div><div class="panel-body"><form class="filters" method="get"><input type="hidden" name="page" value="clients"><div class="field"><label>Buscar</label><input class="input" name="q" value="'.e($q).'"></div><button class="btn btn-dark">Buscar</button></form></div><div class="table-wrap"><table class="table"><tr><th>Cliente</th><th>RUT</th><th>Contacto</th><th>Correo</th><th>Solicitudes</th></tr>';foreach($rows as $c)echo '<tr><td>'.e($c['name']).'</td><td>'.e($c['rut']).'</td><td>'.e($c['contact_name']).'<br>'.e($c['phone']).'</td><td>'.e($c['email']).'</td><td>'.e((string)$c['request_count']).'</td></tr>';echo '</table></div>';if(!$rows)echo '<div class="empty">No hay clientes registrados.</div>';echo '</section>';shell_end();exit; }

if($page==='request'){
    $id=(int)($_GET['id']??0);$s=db()->prepare('SELECT r.*,c.name client_name,c.rut,c.email,c.phone,c.address,c.contact_name FROM quote_requests r JOIN clients c ON c.id=r.client_id WHERE r.id=?');$s->execute([$id]);$r=$s->fetch();if(!$r)exit('Solicitud no encontrada.');$s=db()->prepare('SELECT * FROM request_attachments WHERE request_id=?');$s->execute([$id]);$files=$s->fetchAll();$s=db()->prepare('SELECT * FROM quotes WHERE request_id=?');$s->execute([$id]);$quotes=$s->fetchAll();shell_start('Solicitud',$r['request_number']);echo '<div class="actions"><a class="btn btn-outline" href="index.php?page=requests">← Volver</a>'.(!$quotes?'<a class="btn btn-primary" href="index.php?page=quote_new&request_id='.$id.'">Crear cotización</a>':'').'</div><div class="detail-grid"><section class="panel"><div class="panel-head"><h2>Requerimiento</h2><span class="status '.status_class($r['status']).'">'.e(status_label($r['status'])).'</span></div><div class="panel-body">';foreach([['Servicio',$r['service_product']],['Descripción',$r['technical_description']],['Material',$r['material']?:'No informado'],['Cantidad',($r['quantity']?:'No informada').' '.($r['unit']??'')],['Medidas',$r['measurements']?:'No informadas'],['Plazo',$r['required_deadline']?:'No informado'],['Observaciones',$r['observations']?:'Sin observaciones']] as $kv)echo '<div class="kv"><b>'.e($kv[0]).'</b><span>'.nl2br(e((string)$kv[1])).'</span></div>';echo '</div></section><section class="panel"><div class="panel-head"><h2>Cliente</h2></div><div class="panel-body">';foreach([['Nombre',$r['client_name']],['RUT',$r['rut']],['Contacto',$r['contact_name']],['Correo',$r['email']],['Teléfono',$r['phone']],['Dirección',$r['address']]] as $kv)echo '<div class="kv"><b>'.e($kv[0]).'</b><span>'.e($kv[1]).'</span></div>';echo '</div></section></div><section class="panel"><div class="panel-head"><h2>Actualizar estado</h2></div><div class="panel-body"><form method="post" class="filters"><input type="hidden" name="action" value="request_status"><input type="hidden" name="request_id" value="'.$id.'">'.csrf_field().'<div class="field"><label>Estado</label>';status_select('status',$r['status']);echo '</div><div class="field" style="flex:1"><label>Comentario</label><input class="input" name="comment"></div><button class="btn btn-dark">Guardar</button></form></div></section><section class="panel"><div class="panel-head"><h2>Adjuntos</h2></div><div class="panel-body">';if(!$files)echo '<div class="empty">No hay adjuntos.</div>';foreach($files as $f)echo '<div class="kv"><b>'.e($f['original_name']).'</b><a class="btn btn-outline" href="index.php?action=download_attachment&id='.$f['id'].'">Descargar</a></div>';echo '</div></section>';shell_end();exit;
}
if($page==='quote_new'){ redirect('quote_new.php?request_id='.(int)($_GET['request_id']??0)); }
if($page==='quote_new_legacy'){
    $requestId=(int)($_GET['request_id']??0);$s=db()->prepare('SELECT r.*,c.name client_name FROM quote_requests r JOIN clients c ON c.id=r.client_id WHERE r.id=?');$s->execute([$requestId]);$r=$s->fetch();if(!$r)exit('Solicitud no encontrada.');shell_start('Nueva cotización','Nueva cotización');echo '<form method="post"><input type="hidden" name="action" value="save_quote"><input type="hidden" name="request_id" value="'.$requestId.'">'.csrf_field().'<section class="panel"><div class="panel-head"><h2>'.e($r['client_name']).'</h2></div><div class="panel-body"><div class="form-grid"><div class="field"><label>Fecha emisión</label><input class="input" type="date" name="issue_date" value="'.date('Y-m-d').'" required></div><div class="field"><label>Fecha vencimiento *</label><input class="input" type="date" name="expiry_date" required></div><div class="field full"><label>Notas</label><textarea class="textarea" name="notes"></textarea></div></div></div></section><section class="panel"><div class="panel-head"><h2>Ítems</h2></div><div class="panel-body"><div class="form-grid"><div class="field full"><label>Descripción *</label><input class="input" name="description[]" value="'.e($r['service_product']).'" required></div><div class="field"><label>Cantidad</label><input class="input" name="quantity[]" type="number" step=".001" min=".001" value="'.e((string)($r['quantity']?:1)).'" required></div><div class="field"><label>Unidad</label><input class="input" name="unit[]" value="'.e($r['unit']?:'un').'" required></div><div class="field"><label>Precio unitario</label><input class="input" name="unit_price[]" type="number" step=".01" min="0" required></div><div class="field"><label>Descuento %</label><input class="input" name="discount_percent[]" type="number" step=".01" min="0" max="100" value="0"></div></div><p class="hint">Para agregar más ítems, duplica este bloque en la solicitud POST o utiliza una futura mejora de editor dinámico.</p></div></section><div class="actions"><button class="btn btn-primary">Guardar cotización</button></div></form>';shell_end();exit;
}
if($page==='quote'){
    $id=(int)($_GET['id']??0);$s=db()->prepare('SELECT q.*,c.name client_name,c.rut,c.email,c.phone,c.address,c.contact_name FROM quotes q JOIN quote_requests r ON r.id=q.request_id JOIN clients c ON c.id=r.client_id WHERE q.id=?');$s->execute([$id]);$q=$s->fetch();if(!$q)exit('Cotización no encontrada.');$s=db()->prepare('SELECT * FROM quote_items WHERE quote_id=?');$s->execute([$id]);$items=$s->fetchAll();shell_start('Cotización',$q['quote_number']);echo '<div class="actions"><a class="btn btn-outline" href="index.php?page=quotes">← Volver</a><a class="btn btn-primary" href="index.php?action=pdf&id='.$id.'">Descargar PDF</a></div><section class="print-sheet"><div class="print-header"><div><h1>METALRUBBER LTDA.</h1><p class="hint">Metalmecánica y productos de caucho · Hualpén, Chile</p></div><div class="right"><h1>'.e($q['quote_number']).'</h1>Emisión: '.e($q['issue_date']).'<br>Vencimiento: '.e($q['expiry_date']).'</div></div><div class="box"><strong>Cliente:</strong> '.e($q['client_name']).' · '.e($q['rut']).'<br>'.e($q['contact_name']).' · '.e($q['email']).' · '.e($q['phone']).'<br>'.e($q['address']).'</div><table class="print-table"><tr><th>Descripción</th><th>Cantidad</th><th>Unidad</th><th>Precio</th><th>Desc.</th><th>Total</th></tr>';foreach($items as $i)echo '<tr><td>'.e($i['description']).'</td><td>'.e((string)$i['quantity']).'</td><td>'.e($i['unit']).'</td><td>'.money($i['unit_price']).'</td><td>'.e((string)$i['discount_percent']).'%</td><td>'.money($i['line_total']).'</td></tr>';echo '</table><div class="quote-totals"><div><span>Subtotal</span><strong>'.money($q['subtotal']).'</strong></div><div><span>IVA '.e((string)$q['tax_rate']).'%</span><strong>'.money($q['tax_amount']).'</strong></div><div class="grand"><span>Total</span><strong>'.money($q['total']).'</strong></div></div><div class="box"><strong>Observaciones</strong><br>'.nl2br(e($q['notes']?:'Sin observaciones')).'</div></section><section class="panel no-print"><div class="panel-head"><h2>Actualizar estado</h2><span class="status '.status_class($q['status']).'">'.e(status_label($q['status'])).'</span></div><div class="panel-body"><form method="post" class="filters"><input type="hidden" name="action" value="quote_status"><input type="hidden" name="quote_id" value="'.$id.'">'.csrf_field().'<div class="field"><label>Estado</label>';status_select('status',$q['status']);echo '</div><div class="field" style="flex:1"><label>Comentario</label><input class="input" name="comment"></div><button class="btn btn-dark">Actualizar</button></form></div></section>';shell_end();exit;
}
redirect('index.php?page=dashboard');
