<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/app/bootstrap.php';

$requestId=(int)($_GET['request_id']??0);
$s=db()->prepare('SELECT r.*,c.name client_name,c.phone client_phone,c.email client_email,c.contact_name FROM quote_requests r JOIN clients c ON c.id=r.client_id WHERE r.id=?');
$s->execute([$requestId]); $r=$s->fetch();
if(!$r) exit('Solicitud no encontrada.');
$user=require_login();
function qshell(string $title): void {
    $u=current_user(); echo '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.e($title).' · Cotizaciones Metalrubber</title><link rel="stylesheet" href="assets/style.css"></head><body><div class="shell"><aside class="side"><a class="brand" href="index.php?page=dashboard"><span class="brand-mark">M</span><span><strong>METALRUBBER</strong><small>Cotizaciones</small></span></a><nav class="nav"><a href="index.php?page=dashboard">Panel principal</a><a href="index.php?page=requests">Solicitudes</a><a class="active" href="index.php?page=quotes">Cotizaciones</a><a href="index.php?page=clients">Clientes</a></nav></aside><div class="main"><header class="top"><h1>Nueva cotización</h1><div class="user">'.e($u['name']).' · <a href="logout.php">Salir</a></div></header><main class="content">';
}
qshell('Nueva cotización');
echo '<div class="actions"><a class="btn btn-outline" href="index.php?page=request&id='.$requestId.'">← Volver a solicitud</a></div><form method="post" action="index.php"><input type="hidden" name="action" value="save_quote"><input type="hidden" name="request_id" value="'.$requestId.'">'.csrf_field();
echo '<section class="panel"><div class="panel-head"><h2>Datos generales</h2></div><div class="panel-body"><div class="form-grid"><div class="field"><label>Folio / código</label><input class="input" name="quote_number" value="'.e(next_number('COT','quotes','quote_number')).'" required><small>Editable para conservar folios históricos como 27-261370909.</small></div><div class="field"><label>Fecha de emisión</label><input class="input" type="date" name="issue_date" value="'.date('Y-m-d').'" required></div><div class="field"><label>Fecha de vencimiento *</label><input class="input" type="date" name="expiry_date" required></div><div class="field"><label>Atención</label><input class="input" name="attention_name" value="'.e($r['contact_name']).'"></div><div class="field"><label>Teléfono cliente</label><input class="input" name="client_phone" value="'.e($r['client_phone']).'"></div><div class="field"><label>E-mail cliente</label><input class="input" type="email" name="client_email" value="'.e($r['client_email']).'"></div></div></div></section>';
echo '<section class="panel"><div class="panel-head"><h2>Detalle</h2></div><div class="panel-body table-wrap"><table class="table"><tr><th>Ítem</th><th>Unidad</th><th>Cantidad</th><th>Descripción</th><th>Valor unitario neto</th><th>Descuento %</th></tr>';
for($i=0;$i<8;$i++){ $default=$i===0?$r['service_product']:''; $qty=$i===0&&$r['quantity']?(string)$r['quantity']:''; echo '<tr><td>'.($i+1).'</td><td><input class="input" name="unit[]" value="'.($i===0?e($r['unit']?:'c/u'):'c/u').'"></td><td><input class="input" name="quantity[]" type="number" min="0" step=".001" value="'.e($qty).'"></td><td><input class="input" name="description[]" value="'.e($default).'"></td><td><input class="input" name="unit_price[]" type="number" min="0" step=".01" value="0"></td><td><input class="input" name="discount_percent[]" type="number" min="0" max="100" step=".01" value="0"></td></tr>'; }
echo '</table><small class="hint">Completa solo los ítems utilizados. Los montos se calculan automáticamente al guardar.</small></div></section>';
echo '<section class="panel"><div class="panel-head"><h2>Entrega y pago</h2></div><div class="panel-body"><div class="form-grid"><div class="field"><label>Lugar de entrega</label><input class="input" name="delivery_location"></div><div class="field"><label>Plazo de entrega</label><input class="input" name="delivery_term" placeholder="Ej.: 5 días hábiles"></div><div class="field"><label>Forma de pago</label><input class="input" name="payment_method" placeholder="Ej.: Orden de compra"></div><div class="field full"><label>Observaciones y condiciones</label><textarea class="textarea" name="notes" placeholder="Incluye información técnica, alcance, retiros, entregas u otras condiciones."></textarea></div></div></div></section><div class="actions"><button class="btn btn-primary">Guardar cotización</button></div></form></main></div></div></body></html>';

