<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/app/bootstrap.php';
require_login();
$id=(int)($_GET['id']??0);
$s=db()->prepare('SELECT q.*,c.name client_name,c.rut,c.email,c.phone,c.address,c.contact_name FROM quotes q JOIN quote_requests r ON r.id=q.request_id JOIN clients c ON c.id=r.client_id WHERE q.id=?');$s->execute([$id]);$q=$s->fetch();if(!$q)exit('Cotizacion no encontrada.');
$s=db()->prepare('SELECT * FROM quote_items WHERE quote_id=? ORDER BY id');$s->execute([$id]);$items=$s->fetchAll();
echo '<style>@page{size:A4;margin:0}@media print{body{padding:14mm!important} .toolbar{display:none!important}}</style>';
?><!doctype html><html lang="es"><head><meta charset="utf-8"><title><?=e($q['quote_number'])?></title><style>@page{size:A4;margin:14mm}*{box-sizing:border-box}body{font:12px Arial,sans-serif;color:#17191b;margin:0}.header{border-bottom:7px solid #f7df00;padding:0 0 14px;display:flex;justify-content:space-between}.header h1{font-size:25px;margin:0 0 5px}.right{text-align:right}.box{border:1px solid #ccc;padding:10px;margin:14px 0}table{width:100%;border-collapse:collapse;margin-top:16px}th{background:#25282b;color:#fff;text-align:left}th,td{padding:8px;border-bottom:1px solid #ddd}.totals{margin-left:auto;width:280px;margin-top:14px}.totals div{display:flex;justify-content:space-between;padding:5px}.total{font-weight:bold;font-size:16px;border-top:2px solid #17191b}.toolbar{margin:0 0 20px;display:flex;gap:10px}@media print{.toolbar{display:none}}button,a{padding:10px 14px;border:1px solid #222;background:#fff;color:#111;text-decoration:none;cursor:pointer}button{background:#f7df00;border-color:#f7df00;font-weight:bold}</style></head><body><div class="toolbar"><button onclick="window.print()">Imprimir / Guardar como PDF</button><a href="index.php?page=quote&id=<?=$id?>">Volver</a></div><div class="header"><div><h1>METALRUBBER LTDA.</h1><div>Comercializadora y Maestranza Pedreros y Badilla Ltda.</div><div>Rut: 76.271.277-6 · Autopista #8360, Hualpen · Fono: 41 317 7199</div><div>metalrubber@gmail.com</div></div><div class="right"><h1><?=e($q['quote_number'])?></h1><div>Fecha: <?=e(date_cl($q['issue_date']))?></div><div>Vencimiento: <?=e(date_cl($q['expiry_date']))?></div></div></div><div class="box"><strong>Cliente:</strong> <?=e($q['client_name'])?> · <?=e($q['rut'])?><br><?=e($q['attention_name']??$q['contact_name'])?> · <?=e($q['client_email']??$q['email'])?> · <?=e($q['client_phone']??$q['phone'])?><br><?=e($q['address'])?></div><p>De acuerdo a su solicitud, enviamos la siguiente cotizacion:</p><table><tr><th>Item</th><th>Unidad</th><th>Cantidad</th><th>Descripcion</th><th>Precio unitario neto</th><th>Total neto</th></tr><?php foreach($items as $i=>$item): ?><tr><td><?=$i+1?></td><td><?=e($item['unit'])?></td><td><?=e(quantity($item['quantity']))?></td><td><?=nl2br(e($item['description']))?></td><td><?=money($item['unit_price'])?></td><td><?=money($item['line_total'])?></td></tr><?php endforeach; ?></table><div class="totals"><div><span>Valor Neto</span><strong><?=money($q['subtotal'])?></strong></div><div><span>IVA <?=e((string)$q['tax_rate'])?>%</span><strong><?=money($q['tax_amount'])?></strong></div><div class="total"><span>Total Final</span><strong><?=money($q['total'])?></strong></div></div><div class="box"><strong>Observaciones</strong><br><?=nl2br(e($q['notes']??'Sin observaciones'))?></div></body></html>
