<?php
declare(strict_types=1);
function render_quote_pdf(array $quote,array $items): void {
    $autoload=dirname(__DIR__).'/vendor/autoload.php'; if (!is_file($autoload)) { http_response_code(503); exit('Dompdf no está instalado. Ejecuta composer install en el servidor.'); } require_once $autoload;
    $html='<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;color:#17191b;font-size:11px}h1{font-size:26px;margin:0 0 4px}h2{font-size:14px;border-bottom:2px solid #f7df00;padding-bottom:6px}.header{border-bottom:8px solid #f7df00;padding:16px 0 12px}.right{text-align:right}.box{border:1px solid #d9d9d4;padding:12px;margin:18px 0}.muted{color:#667078}table{width:100%;border-collapse:collapse;margin-top:14px}th{background:#25282b;color:white;text-align:left}th,td{padding:8px;border-bottom:1px solid #ddd}.total{font-size:16px;font-weight:bold}.footer{margin-top:30px;color:#667078;font-size:10px}</style></head><body><div class="header"><h1>METALRUBBER LTDA.</h1><div class="muted">Metalmecánica y productos de caucho · Hualpén, Chile</div><div class="right"><h1>'.e($quote['quote_number']).'</h1>Emisión: '.e($quote['issue_date']).'<br>Vencimiento: '.e($quote['expiry_date']).'</div></div><div class="box"><strong>Cliente:</strong> '.e($quote['client_name']).'<br><strong>RUT:</strong> '.e($quote['rut']).'<br><strong>Contacto:</strong> '.e($quote['contact_name']).' · '.e($quote['email']).' · '.e($quote['phone']).'<br>'.e($quote['address']).'</div><h2>Detalle de la cotización</h2><table><tr><th>Descripción</th><th>Cant.</th><th>Unidad</th><th>Precio unitario</th><th>Desc.</th><th>Total</th></tr>';
    foreach($items as $i) $html.='<tr><td>'.e($i['description']).'</td><td>'.e((string)$i['quantity']).'</td><td>'.e($i['unit']).'</td><td class="right">'.money($i['unit_price']).'</td><td class="right">'.e((string)$i['discount_percent']).'%</td><td class="right">'.money($i['line_total']).'</td></tr>';
    $html.='</table><div class="right box"><div>Subtotal: '.money($quote['subtotal']).'</div><div>IVA ('.e((string)$quote['tax_rate']).'%): '.money($quote['tax_amount']).'</div><div class="total">Total: '.money($quote['total']).'</div></div><div class="box"><strong>Observaciones y condiciones</strong><br>'.nl2br(e($quote['notes']??'')).'</div><div class="footer">Metalrubber Ltda. · 41 317 7199 · WhatsApp +56 9 9312 8000 · metalrubber@gmail.com · metalrubber.cl</div></body></html>';
    $dompdf=new Dompdf\Dompdf(['isRemoteEnabled'=>false]); $dompdf->loadHtml($html,'UTF-8'); $dompdf->setPaper('A4'); $dompdf->render(); $dompdf->stream($quote['quote_number'].'.pdf',['Attachment'=>true]);
}

