<?php
declare(strict_types=1);
function render_quote_pdf(array $quote,array $items): void {
    $autoload=dirname(__DIR__).'/vendor/autoload.php';
    if(!is_file($autoload)){http_response_code(503);exit('Dompdf no está instalado.');}
    require_once $autoload;
    $html='<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;color:#17191b;font-size:10px}h1{font-size:22px;margin:0 0 4px}table{width:100%;border-collapse:collapse;margin-top:12px}th{background:#25282b;color:#fff;text-align:left}th,td{padding:7px;border-bottom:1px solid #ddd}.header{border-bottom:8px solid #f7df00;padding:12px 0;display:flex;justify-content:space-between}.right{text-align:right}.box{border:1px solid #d9d9d4;padding:10px;margin:13px 0}.muted{color:#667078}.total{font-size:15px;font-weight:bold}.footer{margin-top:20px;color:#667078;font-size:9px}</style></head><body><div class="header"><div><h1>METALRUBBER LTDA.</h1><div>Comercializadora y Maestranza Pedreros y Badilla Ltda.</div><div class="muted">Rut: 76.271.277-6 · Giro: Comercializadora y Maestranza<br>Autopista #8360, Hualpén · Fono: 41 317 7199<br>metalrubber@gmail.com</div></div><div class="right"><h1>'.e($quote['quote_number']).'</h1><div>Fecha: '.e($quote['issue_date']).'<br>Vencimiento: '.e($quote['expiry_date']).'</div></div></div><div class="box"><strong>Señores:</strong> '.e($quote['client_name']).'<br><strong>Atención:</strong> '.e($quote['attention_name']??$quote['contact_name']).'<br><strong>Fono:</strong> '.e($quote['client_phone']??$quote['phone']).' · <strong>E-mail:</strong> '.e($quote['client_email']??$quote['email']).'<br>'.e($quote['address']).'</div><p>De acuerdo a su solicitud envío la siguiente cotización:</p><table><tr><th>Ítem</th><th>Un.</th><th>Cant.</th><th>Descripción</th><th>Valor unitario neto</th><th>Valor total neto</th></tr>';
    $n=1;foreach($items as $item){$html.='<tr><td>'.$n++.'</td><td>'.e($item['unit']).'</td><td>'.e((string)$item['quantity']).'</td><td>'.nl2br(e($item['description'])).'</td><td>'.money($item['unit_price']).'</td><td>'.money($item['line_total']).'</td></tr>';}
    $html.='</table><div class="box"><strong>Lugar de entrega:</strong> '.e($quote['delivery_location']??'').'<br><strong>Plazo de entrega:</strong> '.e($quote['delivery_term']??'').'<br><strong>Forma de pago:</strong> '.e($quote['payment_method']??'').'</div><div class="right box"><div>Valor Neto: '.money($quote['subtotal']).'</div><div>IVA '.e((string)$quote['tax_rate']).'%: '.money($quote['tax_amount']).'</div><div class="total">Total Final: '.money($quote['total']).'</div></div><div class="box"><strong>Observaciones</strong><br>'.nl2br(e($quote['notes']??'')).'</div><div class="footer">CARLOS PEDREROS C. · Representante Legal<br>Metalrubber Ltda. · Hualpén, Chile</div></body></html>';
    $dompdf=new Dompdf\Dompdf(['isRemoteEnabled'=>false]);$dompdf->loadHtml($html,'UTF-8');$dompdf->setPaper('A4');$dompdf->render();$dompdf->stream($quote['quote_number'].'.pdf',['Attachment'=>true]);
}

