<!doctype html><html lang="es"><head><meta charset="utf-8"><title><?=e($q['quote_number'])?></title><style>
@page{size:A4;margin:12mm}*{box-sizing:border-box}body{margin:0;color:#111;font-family:DejaVu Sans,Arial,sans-serif;font-size:9pt;line-height:1.35}table{width:100%;border-collapse:collapse;table-layout:fixed}td,th{overflow-wrap:break-word;word-wrap:break-word}.header td{border:0;vertical-align:top;text-align:center;padding:0 0 5mm}.logo{background:#ffe500;border:3px double #111;font-size:21pt;font-weight:bold;padding:3mm 1mm;letter-spacing:1px}.slogan{font-size:8pt;margin-top:2mm}.company{font-size:8pt}.company strong{font-size:13pt}.title{text-align:center;font-size:15pt;margin:5mm 0}.client td{border:1px solid #111;padding:2mm 3mm;vertical-align:top}.intro{font-size:9pt;margin:3mm 0}.items th,.items td{border:1px solid #111;padding:2mm 1mm;vertical-align:top}.items th{text-align:center;font-size:8pt;background:#f3f3f3}.items thead{display:table-header-group}.items tr{page-break-inside:avoid}.numeric{text-align:right;white-space:nowrap}.center{text-align:center}.bottom{page-break-inside:avoid;margin-top:0}.bottom td{border:1px solid #111;padding:2mm;vertical-align:top}.totals td{border:0;padding:1mm}.notes{border:1px solid #111;padding:3mm;margin-top:3mm;page-break-inside:avoid}.signature{text-align:center;margin:15mm auto 0;width:75mm;border-top:1px solid #111;padding-top:2mm;font-weight:bold;page-break-inside:avoid}.toolbar{display:none}h1,p{overflow-wrap:break-word}@media screen{body{max-width:186mm;margin:12mm auto;padding:6mm;background:#fff}.toolbar{display:block;margin-bottom:5mm}.toolbar button,.toolbar a{display:inline-block;padding:8px 12px;border:1px solid #111;color:#111;background:#ffe500;text-decoration:none;font:inherit;cursor:pointer}html{background:#eee}}@media print{.toolbar{display:none}body{padding:0}}
</style></head><body>
<?php if(!empty($printToolbar)):?><div class="toolbar"><button onclick="window.print()">Imprimir / Guardar como PDF</button> <a href="index.php?page=quote&amp;id=<?=(int)$q['id']?>">Volver</a></div><?php endif;?>
<table class="header"><tr><td style="width:46%"><div class="logo">METALRUBBER</div><div class="slogan">Fabricación de Productos de Caucho<br>Plásticos Mecanizados, Maestranza<br>Y Mantenimiento Industrial.</div></td><td style="width:54%" class="company"><strong>METALRUBBER LTDA.</strong><br>Comercializadora y Maestranza Pedreros y Badilla Ltda.<br>Rut: 76.271.277-6<br>Giro: Comercializadora y Maestranza<br>Autopista #8360, Hualpén<br>Fono: 041-3177199<br>metalrubber@gmail.com</td></tr></table>
<h1 class="title">COTIZACIÓN N° <?=e($q['quote_number'])?></h1>
<table class="client"><tr><td style="width:62%"><strong>Señores:</strong> <?=e($q['client_name'])?><br><strong>Atención:</strong> <?=e($q['attention_name']??'')?><?=!empty($q['contact_area'])?' — '.e($q['contact_area']):''?><br><strong>RUT:</strong> <?=e($q['rut'])?><br><strong>Dirección:</strong> <?=e($q['address'])?></td><td style="width:38%"><strong>Fecha:</strong> <?=e(date_cl($q['issue_date']))?><br><strong>Fono:</strong> <?=e($q['client_phone']??$q['phone'])?><br><strong>E-mail:</strong> <?=e($q['client_email']??$q['email'])?></td></tr></table>
<p class="intro">De acuerdo a su solicitud envío la siguiente cotización:</p>
<table class="items"><thead><tr><th style="width:6%;white-space:nowrap">Ítem</th><th style="width:5%">Un</th><th style="width:7%">Cant</th><th style="width:44%">Descripción</th><th style="width:18%">Valor unitario</th><th style="width:20%">Valor Total Neto</th></tr></thead><tbody>
<?php foreach($items as $i=>$item):?><tr><td class="center"><?=$i+1?></td><td class="center"><?=e($item['unit'])?></td><td class="numeric"><?=e(quantity($item['quantity']))?></td><td><?=nl2br(e($item['description']))?><?php if((float)$item['discount_percent']>0):?><br><small>Descuento: <?=e(quantity($item['discount_percent']))?>%</small><?php endif;?></td><td class="numeric"><?=money($item['unit_price'])?></td><td class="numeric"><?=money($item['line_total'])?></td></tr><?php endforeach;?>
<?php if(count($items)<=3):?><tr><td style="height:45mm"></td><td></td><td></td><td></td><td></td><td></td></tr><?php endif;?></tbody></table>
<table class="bottom"><tr><td style="width:62%"><strong>Lugar de entrega:</strong> <?=e($q['delivery_location']??'')?><br><strong>Plazo de Entrega:</strong> <?=e($q['delivery_term']??'')?><br><strong>Forma de Pago:</strong> <?=e($q['payment_method']??'')?></td><td style="width:38%"><table class="totals"><tr><td>Valor Neto</td><td class="numeric"><strong><?=money($q['subtotal'])?></strong></td></tr><tr><td>IVA 19%</td><td class="numeric"><strong><?=money($q['tax_amount'])?></strong></td></tr><tr><td><strong>Total Final</strong></td><td class="numeric"><strong><?=money($q['total'])?></strong></td></tr></table></td></tr></table>
<div class="notes"><strong>Vigencia:</strong> <?=(new DateTimeImmutable($q['issue_date']))->diff(new DateTimeImmutable($q['expiry_date']))->days?> días corridos desde la emisión. Vence el <?=e(date_cl($q['expiry_date']))?>.<br><strong>Observaciones:</strong><br><?=nl2br(e($q['notes']??''))?></div>
<div class="signature">CARLOS PEDREROS C.<br>Representante Legal</div>
</body></html>
